// This file was generated by silverstripe/cow from client/lang/src/ar.json.
// See https://github.com/silverstripe/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ar', {
    "HistoryViewer.NEXT": "التالي",
    "HistoryViewer.PREVIOUS": "السابق",
    "HistoryViewer.COMPARE_MODE": "وضعية المقارنة",
    "HistoryViewer.SELECT_PROMPT": "اختر نسختين",
    "HistoryViewer.EXIT": "خروج",
    "HistoryViewerHeading.COMPARE_VERSIONS": "مقارنة نسختين",
    "HistoryViewer.Record": "سجل",
    "HistoryViewer.Author": "المؤلف",
    "HistoryViewerToolbar.REVERT_UNAVAILABLE": "غير متاح في النسخة الحالية",
    "HistoryViewerToolbar.REVERT_TO_VERSION": "استرجاع هذه النسخة",
    "HistoryViewerToolbar.REVERTED_MESSAGE": "تم استرجاع النسخة %s",
    "HistoryViewerVersion.COMPARE": "مقارنة",
    "HistoryViewerVersion.CLOSE": "إغلاق",
    "HistoryViewerVersion.SELECTED": "مختارة بالفعل",
    "HistoryViewerVersion.GO_TO_VERSION": "اذهب إلى النسخة {version}",
    "HistoryViewerVersionList.CLOSE": "إغلاق",
    "HistoryViewer.Published": "تم النشر",
    "HistoryViewer.Saved": "تم الحفظ",
    "HistoryViewer.BadgeLive": "مباشر"
});
}