// This file was generated by silverstripe/cow from client/lang/src/en.json.
// See https://github.com/silverstripe/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "HistoryViewer.NEXT": "Next",
    "HistoryViewer.PREVIOUS": "Previous",
    "HistoryViewer.COMPARE_MODE": "Compare mode",
    "HistoryViewer.SELECT_PROMPT": "Select two versions",
    "HistoryViewer.EXIT": "Exit",
    "HistoryViewerHeading.COMPARE_VERSIONS": "Compare two versions",
    "HistoryViewer.Record": "Record",
    "HistoryViewer.Author": "Author",
    "HistoryViewerToolbar.REVERT_UNAVAILABLE": "Unavailable for the current version",
    "HistoryViewerToolbar.REVERT_TO_VERSION": "Revert to this version",
    "HistoryViewerToolbar.REVERTED_MESSAGE": "Successfully reverted to version %s",
    "HistoryViewerVersion.COMPARE": "Compare",
    "HistoryViewerVersion.CLOSE": "Close",
    "HistoryViewerVersion.SELECTED": "Already selected",
    "HistoryViewerVersion.GO_TO_VERSION": "Go to version {version}",
    "HistoryViewerVersionList.CLOSE": "Close",
    "HistoryViewer.Published": "Published",
    "HistoryViewer.Saved": "Saved",
    "HistoryViewer.BadgeLive": "Live"
});
}