// This file was generated by silverstripe/cow from client/lang/src/fr.json.
// See https://github.com/silverstripe/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fr', {
    "HistoryViewer.NEXT": "Suivant",
    "HistoryViewer.PREVIOUS": "Précédant",
    "HistoryViewer.COMPARE_MODE": "Mode de comparaison",
    "HistoryViewer.SELECT_PROMPT": "Sélectionner deux versions",
    "HistoryViewer.EXIT": "Quitter",
    "HistoryViewerHeading.COMPARE_VERSIONS": "Comparer deux versions",
    "HistoryViewer.Record": "Entrée",
    "HistoryViewer.Author": "Auteur",
    "HistoryViewerToolbar.REVERT_UNAVAILABLE": "Non disponible pour cette version",
    "HistoryViewerToolbar.REVERT_TO_VERSION": "Rétablir cette version",
    "HistoryViewerToolbar.REVERTED_MESSAGE": "Version %s rétablie avec succès ",
    "HistoryViewerVersion.COMPARE": "Comparer",
    "HistoryViewerVersion.CLOSE": "Fermer",
    "HistoryViewerVersion.SELECTED": "Déjà selectionné",
    "HistoryViewerVersion.GO_TO_VERSION": "Aller à la version {version}",
    "HistoryViewerVersionList.CLOSE": "Fermer",
    "HistoryViewer.Published": "Publié",
    "HistoryViewer.Saved": "Sauvegardé",
    "HistoryViewer.BadgeLive": "Actif"
});
}