// This file was generated by silverstripe/tx-translator from client/lang/src/it.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('it', {
    "HistoryViewer.Author": "Autore",
    "HistoryViewer.COMPARE_MODE": "Modalità comparazione",
    "HistoryViewer.EXIT": "Uscita",
    "HistoryViewer.NEXT": "Prossimo",
    "HistoryViewer.PREVIOUS": "Precedente",
    "HistoryViewer.Published": "Pubblicato",
    "HistoryViewer.SELECT_PROMPT": "Selezionare due versioni",
    "HistoryViewer.Saved": "Salvato",
    "HistoryViewerHeading.COMPARE_VERSIONS": "Comparare due versioni",
    "HistoryViewerToolbar.REVERTED_MESSAGE": "Versione %s ripristinata con successo",
    "HistoryViewerToolbar.REVERT_TO_VERSION": "Ripristinare a questa versione",
    "HistoryViewerToolbar.REVERT_UNAVAILABLE": "Non disponibile nella versione corrente",
    "HistoryViewerVersion.CLOSE": "Chiudi",
    "HistoryViewerVersion.COMPARE": "Comparare",
    "HistoryViewerVersion.GO_TO_VERSION": "Andare alla versione {version}",
    "HistoryViewerVersion.SELECTED": "Già selezionato",
    "HistoryViewerVersionList.CLOSE": "Chiudi"
});
}