// This file was generated by silverstripe/cow from client/lang/src/nl.json.
// See https://github.com/silverstripe/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "HistoryViewer.NEXT": "Volgende",
    "HistoryViewer.PREVIOUS": "Vorige",
    "HistoryViewer.COMPARE_MODE": "Vergelijken",
    "HistoryViewer.SELECT_PROMPT": "Selecteer 2 versies",
    "HistoryViewer.EXIT": "Exit",
    "HistoryViewerHeading.COMPARE_VERSIONS": "Vergelijk 2 versies",
    "HistoryViewer.Record": "Versie",
    "HistoryViewer.Author": "Auteur",
    "HistoryViewerToolbar.REVERT_UNAVAILABLE": "Niet beschikbaar voor de huidige versie",
    "HistoryViewerToolbar.REVERT_TO_VERSION": "Keer terug naar deze versie",
    "HistoryViewerToolbar.REVERTED_MESSAGE": "Succesvol teruggekeerd naar versie %s",
    "HistoryViewerVersion.COMPARE": "Vergelijk",
    "HistoryViewerVersion.CLOSE": "Sluit",
    "HistoryViewerVersion.SELECTED": "Reeds geselecteerd",
    "HistoryViewerVersion.GO_TO_VERSION": "Ga naar versie {version}",
    "HistoryViewerVersionList.CLOSE": "Sluit",
    "HistoryViewer.Published": "Gepubliceerd ",
    "HistoryViewer.Saved": "Opgeslagen",
    "HistoryViewer.BadgeLive": "Live"
});
}