// This file was generated by silverstripe/tx-translator from client/lang/src/pl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('pl', {
    "HistoryViewer.Author": "Autor",
    "HistoryViewer.BadgeLive": "Na żywo",
    "HistoryViewer.EXIT": "Wyjdź",
    "HistoryViewer.NEXT": "Następny",
    "HistoryViewer.PREVIOUS": "Poprzedni",
    "HistoryViewer.Published": "Opublikowano",
    "HistoryViewer.Record": "Rekord",
    "HistoryViewer.SELECT_PROMPT": "Zaznacz dwie wersje",
    "HistoryViewer.Saved": "Zapisano",
    "HistoryViewerHeading.COMPARE_VERSIONS": "Porównaj dwie wersje",
    "HistoryViewerToolbar.REVERTED_MESSAGE": "Pomyślnie przywrócono do wersji %s",
    "HistoryViewerToolbar.REVERT_TO_VERSION": "Wróć do tej wersji",
    "HistoryViewerToolbar.REVERT_UNAVAILABLE": "Niedostępne w obecnej wersji",
    "HistoryViewerVersion.CLOSE": "Zamknij",
    "HistoryViewerVersion.COMPARE": "Porównaj",
    "HistoryViewerVersion.GO_TO_VERSION": "Wróć do wersji {version}",
    "HistoryViewerVersion.SELECTED": "Już zaznaczono",
    "HistoryViewerVersionList.CLOSE": "Zamknij"
});
}