// This file was generated by silverstripe/cow from client/lang/src/sl.json.
// See https://github.com/silverstripe/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl', {
    "HistoryViewer.NEXT": "Naslednja",
    "HistoryViewer.PREVIOUS": "Pretekla",
    "HistoryViewer.COMPARE_MODE": "Primerjava",
    "HistoryViewer.SELECT_PROMPT": "Izberite dve različici",
    "HistoryViewer.EXIT": "Izhod",
    "HistoryViewerHeading.COMPARE_VERSIONS": "Primerjajte dve različici",
    "HistoryViewer.Record": "Zapis",
    "HistoryViewer.Author": "Avtor",
    "HistoryViewerToolbar.REVERT_UNAVAILABLE": "Ni na voljo za izbrano različico",
    "HistoryViewerToolbar.REVERT_TO_VERSION": "Povrni izbrano različico",
    "HistoryViewerToolbar.REVERTED_MESSAGE": "Povrnili smo v različico %s",
    "HistoryViewerVersion.COMPARE": "Primerjaj",
    "HistoryViewerVersion.CLOSE": "Zapri",
    "HistoryViewerVersion.SELECTED": "Že izbrana",
    "HistoryViewerVersion.GO_TO_VERSION": "Pojdi na različico {version}",
    "HistoryViewerVersionList.CLOSE": "Zapri",
    "HistoryViewer.Published": "Objavljeno",
    "HistoryViewer.Saved": "Shranjeno",
    "HistoryViewer.BadgeLive": "Javno"
});
}